package erpscm.modelscm.scmvo;

import erpscm.modelscm.scmvo.common.ScmPurchaseRfqLinesVO;

import oracle.jbo.Row;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Oct 09 11:36:26 PKT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ScmPurchaseRfqLinesVOImpl extends ViewObjectImpl implements ScmPurchaseRfqLinesVO {
    /**
     * This is the default constructor (do not remove).
     */
    public ScmPurchaseRfqLinesVOImpl() {
    }

    /**
     * Returns the variable value for P_ADF_SUPPLIER_SNO.
     * @return variable value for P_ADF_SUPPLIER_SNO
     */
    public Integer getP_ADF_SUPPLIER_SNO() {
        return (Integer) ensureVariableManager().getVariableValue("P_ADF_SUPPLIER_SNO");
    }

    /**
     * Sets <code>value</code> for variable P_ADF_SUPPLIER_SNO.
     * @param value value to bind as P_ADF_SUPPLIER_SNO
     */
    public void setP_ADF_SUPPLIER_SNO(Integer value) {
        ensureVariableManager().setVariableValue("P_ADF_SUPPLIER_SNO", value);
    }
    
    public void doERPGenerateBidFromRFQ() {
        
        this.setRangeSize(-1);
        ViewObject rfqvo=this.getApplicationModule().findViewObject("ScmPurchaseRfqHeaderCRUD");
        Row rfqRow=rfqvo.getCurrentRow();

        ViewObject bidvoForInsert=this.getApplicationModule().findViewObject("ScmPurchaseBidHeaderRO");
        
        Row newRow=bidvoForInsert.createRow();
        newRow.setAttribute("RfqHeaderSno",rfqRow.getAttribute("RfqHeaderSno"));
        newRow.setAttribute("SupplierSno",rfqRow.getAttribute("SupplierSno"));
        newRow.setAttribute("DemandHeaderSno",rfqRow.getAttribute("DemandHeaderSno"));
        newRow.setAttribute("CompanyId",rfqRow.getAttribute("CompanyId"));
        newRow.setAttribute("TempProjectId",rfqRow.getAttribute("TempProjectId"));
        newRow.setAttribute("TempDepartmentId",rfqRow.getAttribute("TempDepartmentId"));
        newRow.setAttribute("ApprovalStatusSno",2);
        bidvoForInsert.insertRow(newRow);
        
        for (int i = 0; i < this.getRowCount(); i++) {
            Row nextRow=this.getRowAtRangeIndex(i);
            if (nextRow.getAttribute("txtGenerateBID")!=null && nextRow.getAttribute("txtGenerateBID").toString().equals("Y") ) {
                System.out.println(nextRow.getAttribute("txtUnitTypeName"));
           }
        }
        getDBTransaction().commit();
    }

}

