package erpscm.modelscm.scmvo;

import erpglobals.modelglobals.ERPViewRowImpl;

import erpscm.modelscm.scmeo.ScmPurchaseOrderHeaderImpl;

import java.sql.Timestamp;

import oracle.jbo.ApplicationModule;
import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.RowSetIterator;
import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat May 27 11:30:02 PKT 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ScmPurchaseOrderHeaderVORowImpl extends ERPViewRowImpl {


    public static final int ENTITY_SCMPURCHASEORDERHEADER = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        PoHeaderSno,
        PoHeaderCode,
        RfqHeaderSno,
        EmployeeSno,
        ReferenceNo,
        BillToSno,
        ShipToSno,
        DemandHeaderSno,
        CompareHeaderSno,
        PoDate,
        OrderTypeSno,
        StatusId,
        SupplierSno,
        Remarks,
        LocationId,
        GlobalCompanyId,
        CompanyId,
        TempProjectId,
        TempDepartmentId,
        CreatedBy,
        CreatedDate,
        LastUpdatedBy,
        LastUpdatedDate,
        IsSupervised,
        SupervisedBy,
        SupervisedDate,
        IsUnsupervised,
        UnSupervisedBy,
        UnSupervisedDate,
        IsCancelled,
        CancelledBy,
        CancelledDate,
        ApprovalStatusSno,
        PoTypeSno,
        FobTermSno,
        FreightTermSno,
        CourierSno,
        PaymentTermHeaderSno,
        txtLocationName,
        txtTempDepartmentName,
        txtTempProjectName,
        txtPaymentTermName,
        txtFreightTermName,
        txtFobTermName,
        txtRfqHeaderCode,
        txtDemandHeaderCode,
        txtSupplierName,
        txtSupplierBillToLocation,
        txtSupplierShipToLocation,
        DeliveryTermSno,
        txtDeliveryTermName,
        txtOrderTypeName,
        ScmPurchaseOrderChargesVO,
        ScmPurchaseOrderDiscountVO,
        ScmPurchaseOrderLinesVO,
        AdminCompanyVO,
        AdminCompanyVO1,
        GlProjectsVO,
        ScmPurchaseRfqHeaderVO,
        ScmPaymentTermHeaderVO,
        ScmFreightTermVO,
        ScmFobTermVO,
        ScmPurchaseDemandHeaderVO,
        ScmSupplierSitesVO,
        ScmSupplierSitesVO1,
        ScmDeliveryTermVO,
        ScmOrderTypeVO,
        ScmSupplierVO,
        AccSysGeneralValuePOTypeVO,
        AccSysSystemParameterVO,
        AccAdminCompanyForCompVO,
        AccGlProjectsVO,
        AccScmPaymentTermHeaderVO,
        AccScmFreightTermVO,
        AccScmFobTermVO,
        AccScmPurchaseRfqHeaderVO,
        AccScmPurchaseDemandHeaderVO,
        AccAdminCompanyVO,
        AccScmSupplierVO,
        AccAdminCompanyDept,
        AccSysApprovalStatusVO,
        AccScmSupplierSitesVO,
        AccScmSupplierSitesShipToVO,
        AccScmDeliveryTermVO,
        AccScmOrderTypeVO,
        AccScmPurchaseBidCompHeaderVO,
        AccScmPurchaseBidCompSupplierVO,
        AccScmPurchaseBidLinesVO;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int POHEADERSNO = AttributesEnum.PoHeaderSno.index();
    public static final int POHEADERCODE = AttributesEnum.PoHeaderCode.index();
    public static final int RFQHEADERSNO = AttributesEnum.RfqHeaderSno.index();
    public static final int EMPLOYEESNO = AttributesEnum.EmployeeSno.index();
    public static final int REFERENCENO = AttributesEnum.ReferenceNo.index();
    public static final int BILLTOSNO = AttributesEnum.BillToSno.index();
    public static final int SHIPTOSNO = AttributesEnum.ShipToSno.index();
    public static final int DEMANDHEADERSNO = AttributesEnum.DemandHeaderSno.index();
    public static final int COMPAREHEADERSNO = AttributesEnum.CompareHeaderSno.index();
    public static final int PODATE = AttributesEnum.PoDate.index();
    public static final int ORDERTYPESNO = AttributesEnum.OrderTypeSno.index();
    public static final int STATUSID = AttributesEnum.StatusId.index();
    public static final int SUPPLIERSNO = AttributesEnum.SupplierSno.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int LOCATIONID = AttributesEnum.LocationId.index();
    public static final int GLOBALCOMPANYID = AttributesEnum.GlobalCompanyId.index();
    public static final int COMPANYID = AttributesEnum.CompanyId.index();
    public static final int TEMPPROJECTID = AttributesEnum.TempProjectId.index();
    public static final int TEMPDEPARTMENTID = AttributesEnum.TempDepartmentId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int ISSUPERVISED = AttributesEnum.IsSupervised.index();
    public static final int SUPERVISEDBY = AttributesEnum.SupervisedBy.index();
    public static final int SUPERVISEDDATE = AttributesEnum.SupervisedDate.index();
    public static final int ISUNSUPERVISED = AttributesEnum.IsUnsupervised.index();
    public static final int UNSUPERVISEDBY = AttributesEnum.UnSupervisedBy.index();
    public static final int UNSUPERVISEDDATE = AttributesEnum.UnSupervisedDate.index();
    public static final int ISCANCELLED = AttributesEnum.IsCancelled.index();
    public static final int CANCELLEDBY = AttributesEnum.CancelledBy.index();
    public static final int CANCELLEDDATE = AttributesEnum.CancelledDate.index();
    public static final int APPROVALSTATUSSNO = AttributesEnum.ApprovalStatusSno.index();
    public static final int POTYPESNO = AttributesEnum.PoTypeSno.index();
    public static final int FOBTERMSNO = AttributesEnum.FobTermSno.index();
    public static final int FREIGHTTERMSNO = AttributesEnum.FreightTermSno.index();
    public static final int COURIERSNO = AttributesEnum.CourierSno.index();
    public static final int PAYMENTTERMHEADERSNO = AttributesEnum.PaymentTermHeaderSno.index();
    public static final int TXTLOCATIONNAME = AttributesEnum.txtLocationName.index();
    public static final int TXTTEMPDEPARTMENTNAME = AttributesEnum.txtTempDepartmentName.index();
    public static final int TXTTEMPPROJECTNAME = AttributesEnum.txtTempProjectName.index();
    public static final int TXTPAYMENTTERMNAME = AttributesEnum.txtPaymentTermName.index();
    public static final int TXTFREIGHTTERMNAME = AttributesEnum.txtFreightTermName.index();
    public static final int TXTFOBTERMNAME = AttributesEnum.txtFobTermName.index();
    public static final int TXTRFQHEADERCODE = AttributesEnum.txtRfqHeaderCode.index();
    public static final int TXTDEMANDHEADERCODE = AttributesEnum.txtDemandHeaderCode.index();
    public static final int TXTSUPPLIERNAME = AttributesEnum.txtSupplierName.index();
    public static final int TXTSUPPLIERBILLTOLOCATION = AttributesEnum.txtSupplierBillToLocation.index();
    public static final int TXTSUPPLIERSHIPTOLOCATION = AttributesEnum.txtSupplierShipToLocation.index();
    public static final int DELIVERYTERMSNO = AttributesEnum.DeliveryTermSno.index();
    public static final int TXTDELIVERYTERMNAME = AttributesEnum.txtDeliveryTermName.index();
    public static final int TXTORDERTYPENAME = AttributesEnum.txtOrderTypeName.index();
    public static final int SCMPURCHASEORDERCHARGESVO = AttributesEnum.ScmPurchaseOrderChargesVO.index();
    public static final int SCMPURCHASEORDERDISCOUNTVO = AttributesEnum.ScmPurchaseOrderDiscountVO.index();
    public static final int SCMPURCHASEORDERLINESVO = AttributesEnum.ScmPurchaseOrderLinesVO.index();
    public static final int ADMINCOMPANYVO = AttributesEnum.AdminCompanyVO.index();
    public static final int ADMINCOMPANYVO1 = AttributesEnum.AdminCompanyVO1.index();
    public static final int GLPROJECTSVO = AttributesEnum.GlProjectsVO.index();
    public static final int SCMPURCHASERFQHEADERVO = AttributesEnum.ScmPurchaseRfqHeaderVO.index();
    public static final int SCMPAYMENTTERMHEADERVO = AttributesEnum.ScmPaymentTermHeaderVO.index();
    public static final int SCMFREIGHTTERMVO = AttributesEnum.ScmFreightTermVO.index();
    public static final int SCMFOBTERMVO = AttributesEnum.ScmFobTermVO.index();
    public static final int SCMPURCHASEDEMANDHEADERVO = AttributesEnum.ScmPurchaseDemandHeaderVO.index();
    public static final int SCMSUPPLIERSITESVO = AttributesEnum.ScmSupplierSitesVO.index();
    public static final int SCMSUPPLIERSITESVO1 = AttributesEnum.ScmSupplierSitesVO1.index();
    public static final int SCMDELIVERYTERMVO = AttributesEnum.ScmDeliveryTermVO.index();
    public static final int SCMORDERTYPEVO = AttributesEnum.ScmOrderTypeVO.index();
    public static final int SCMSUPPLIERVO = AttributesEnum.ScmSupplierVO.index();
    public static final int ACCSYSGENERALVALUEPOTYPEVO = AttributesEnum.AccSysGeneralValuePOTypeVO.index();
    public static final int ACCSYSSYSTEMPARAMETERVO = AttributesEnum.AccSysSystemParameterVO.index();
    public static final int ACCADMINCOMPANYFORCOMPVO = AttributesEnum.AccAdminCompanyForCompVO.index();
    public static final int ACCGLPROJECTSVO = AttributesEnum.AccGlProjectsVO.index();
    public static final int ACCSCMPAYMENTTERMHEADERVO = AttributesEnum.AccScmPaymentTermHeaderVO.index();
    public static final int ACCSCMFREIGHTTERMVO = AttributesEnum.AccScmFreightTermVO.index();
    public static final int ACCSCMFOBTERMVO = AttributesEnum.AccScmFobTermVO.index();
    public static final int ACCSCMPURCHASERFQHEADERVO = AttributesEnum.AccScmPurchaseRfqHeaderVO.index();
    public static final int ACCSCMPURCHASEDEMANDHEADERVO = AttributesEnum.AccScmPurchaseDemandHeaderVO.index();
    public static final int ACCADMINCOMPANYVO = AttributesEnum.AccAdminCompanyVO.index();
    public static final int ACCSCMSUPPLIERVO = AttributesEnum.AccScmSupplierVO.index();
    public static final int ACCADMINCOMPANYDEPT = AttributesEnum.AccAdminCompanyDept.index();
    public static final int ACCSYSAPPROVALSTATUSVO = AttributesEnum.AccSysApprovalStatusVO.index();
    public static final int ACCSCMSUPPLIERSITESVO = AttributesEnum.AccScmSupplierSitesVO.index();
    public static final int ACCSCMSUPPLIERSITESSHIPTOVO = AttributesEnum.AccScmSupplierSitesShipToVO.index();
    public static final int ACCSCMDELIVERYTERMVO = AttributesEnum.AccScmDeliveryTermVO.index();
    public static final int ACCSCMORDERTYPEVO = AttributesEnum.AccScmOrderTypeVO.index();
    public static final int ACCSCMPURCHASEBIDCOMPHEADERVO = AttributesEnum.AccScmPurchaseBidCompHeaderVO.index();
    public static final int ACCSCMPURCHASEBIDCOMPSUPPLIERVO = AttributesEnum.AccScmPurchaseBidCompSupplierVO.index();
    public static final int ACCSCMPURCHASEBIDLINESVO = AttributesEnum.AccScmPurchaseBidLinesVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ScmPurchaseOrderHeaderVORowImpl() {
    }

    /**
     * Gets ScmPurchaseOrderHeader entity object.
     * @return the ScmPurchaseOrderHeader
     */
    public ScmPurchaseOrderHeaderImpl getScmPurchaseOrderHeader() {
        return (ScmPurchaseOrderHeaderImpl) getEntity(ENTITY_SCMPURCHASEORDERHEADER);
    }

    /**
     * Gets the attribute value for PO_HEADER_SNO using the alias name PoHeaderSno.
     * @return the PO_HEADER_SNO
     */
    public Integer getPoHeaderSno() {
        return (Integer) getAttributeInternal(POHEADERSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for PO_HEADER_SNO using the alias name PoHeaderSno.
     * @param value value to set the PO_HEADER_SNO
     */
    public void setPoHeaderSno(Integer value) {
        setAttributeInternal(POHEADERSNO, value);
    }

    /**
     * Gets the attribute value for PO_HEADER_CODE using the alias name PoHeaderCode.
     * @return the PO_HEADER_CODE
     */
    public Integer getPoHeaderCode() {
        return (Integer) getAttributeInternal(POHEADERCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for PO_HEADER_CODE using the alias name PoHeaderCode.
     * @param value value to set the PO_HEADER_CODE
     */
    public void setPoHeaderCode(Integer value) {
        setAttributeInternal(POHEADERCODE, value);
    }

    /**
     * Gets the attribute value for RFQ_HEADER_SNO using the alias name RfqHeaderSno.
     * @return the RFQ_HEADER_SNO
     */
    public Integer getRfqHeaderSno() {
        return (Integer) getAttributeInternal(RFQHEADERSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for RFQ_HEADER_SNO using the alias name RfqHeaderSno.
     * @param value value to set the RFQ_HEADER_SNO
     */
    public void setRfqHeaderSno(Integer value) {
        setAttributeInternal(RFQHEADERSNO, value);
        while(getScmPurchaseOrderLinesVO().getRowCount()>0) {
            getScmPurchaseOrderLinesVO().first().remove();
        }
        if (value==null) {
           return;
       }
        ApplicationModule am = getApplicationModule();
        ViewObject erpPOHeadvo=am.findViewObject("ScmPurchaseOrderHeaderCRUD");
        ViewObject erpPOLinesvo=am.findViewObject("ScmPurchaseOrderLinesDetCRUD");
        
        getAccScmPurchaseBidCompHeaderVO().setNamedWhereClauseParam("P_ADF_RFQ_HEADER_SNO", value==null?-1:value);
        getAccScmPurchaseBidCompHeaderVO().executeQuery();
        //fetching data from bid comparison table
        if (getAccScmPurchaseBidCompHeaderVO().getEstimatedRowCount()>0) {
           setAttributeInternal(COMPAREHEADERSNO, getAccScmPurchaseBidCompHeaderVO().first().getAttribute("CompareHeaderSno"));
           getAccScmPurchaseBidCompSupplierVO().setNamedWhereClauseParam("P_ADF_COMPARE_HEADER_SNO",getAccScmPurchaseBidCompHeaderVO().first().getAttribute("CompareHeaderSno") );
           getAccScmPurchaseBidCompSupplierVO().setNamedWhereClauseParam("P_ADF_SUPPLIER_SNO", getSupplierSno()==null?-1:getSupplierSno());
           getAccScmPurchaseBidCompSupplierVO().setNamedWhereClauseParam("P_ADF_RFQ_HEADER_SNO", value==null?-1:value);
           getAccScmPurchaseBidCompSupplierVO().executeQuery();
           RowSetIterator rsi=getAccScmPurchaseBidCompSupplierVO();
           while(rsi.hasNext()) {
               Row bidCompRow=rsi.next();
                    Row erpPoLinRow = erpPOLinesvo.createRow();
                    erpPoLinRow.setAttribute("ItemId", bidCompRow.getAttribute("txtItemId"));
                    erpPoLinRow.setAttribute("UnitTypeSno", bidCompRow.getAttribute("txtUnitTypeSno"));
                    erpPoLinRow.setAttribute("PoRequestQuantity", bidCompRow.getAttribute("RemainingBalance"));
                    erpPoLinRow.setAttribute("PoApproveQuantity", bidCompRow.getAttribute("RemainingBalance"));
                    erpPoLinRow.setAttribute("PoRate", bidCompRow.getAttribute("Rate"));
                    erpPoLinRow.setAttribute("RfqLinesSno", bidCompRow.getAttribute("RfqLinesSno"));
                    erpPoLinRow.setAttribute("DemandLinesSno", bidCompRow.getAttribute("DemandLinesSno"));
                    erpPoLinRow.setAttribute("BidLinesSno", bidCompRow.getAttribute("BidLinesSno"));
                    erpPoLinRow.setAttribute("ProjectId", bidCompRow.getAttribute("txtProjectId"));
                    erpPoLinRow.setAttribute("DepartmentId", bidCompRow.getAttribute("txtDepartmentId"));
                    erpPoLinRow.setAttribute("CompareSupplierSno", bidCompRow.getAttribute("CompareSupplierSno"));
                    erpPoLinRow.setAttribute("InventoryOrgSno", bidCompRow.getAttribute("txtInventoryOrgSno"));
                    erpPoLinRow.setAttribute("SubinventoryOrgSno", bidCompRow.getAttribute("txtSubinventoryOrgSno"));
                    erpPoLinRow.setAttribute("ChartOfAccountId", bidCompRow.getAttribute("txtChartOfAccountId"));
                    erpPoLinRow.setAttribute("LineNo", erpPOLinesvo.getRowCount());
//                    suprow.setAttribute("RemainingBalance", (suprow.getAttribute("txtRemainingQtyForPO" )));
                    erpPOLinesvo.insertRow(erpPoLinRow);
           }
       }
//        
        else if(getDemandHeaderSno()==null){
            getAccScmPurchaseBidLinesVO().setNamedWhereClauseParam("P_RFQ_HEADER_SNO", value==null?-1:value);
            getAccScmPurchaseBidLinesVO().setNamedWhereClauseParam("P_SUPPLIER_SNO", getSupplierSno()==null?-1:getSupplierSno());
            String padfWhereClause="not exists( ";
            padfWhereClause+="select null from scm_purchase_order_header poh,";
            padfWhereClause+=" scm_purchase_order_lines pol where poh.po_header_sno=pol.po_header_sno ";
            padfWhereClause+=" and pol.rfq_lines_sno=scmpurchasebidlines.rfq_lines_sno ";
            padfWhereClause+=" and poh.supplier_sno="+getSupplierSno()+" and poh.rfq_header_sno="+value+") ";
            getAccScmPurchaseBidLinesVO().getViewObject().setWhereClause(padfWhereClause);
            getAccScmPurchaseBidLinesVO().executeQuery();
            System.out.println(getAccScmPurchaseBidLinesVO().getViewObject().getQuery());
            
            
//            getAccScmPurchaseBidHeaderVO().executeQuery();
//            RowSetIterator rsi=getAccScmPurchaseBidHeaderVO();
            /**/
//            while(rsi.hasNext()) {
//                Row erpRfqrow=rsi.next();
//                Row newRow=getScmPurchaseOrderLinesVO().createRow();
//                newRow.setAttribute("RfqLinesSno", erpRfqrow.getAttribute("RfqLinesSno"));
//                newRow.setAttribute("BidLinesSno", erpRfqrow.getAttribute("BidLinesSno"));
//                newRow.setAttribute("ItemId", erpRfqrow.getAttribute("ItemId"));
//                newRow.setAttribute("UnitTypeSno", erpRfqrow.getAttribute("UnitTypeSno"));
//                newRow.setAttribute("Quantity", erpRfqrow.getAttribute("Quantity"));
//                newRow.setAttribute("BidPrice", erpRfqrow.getAttribute("AproxPrice"));
//                System.out.println(erpRfqrow.getAttribute("AproxPrice") +"<aaprice");
//                newRow.setAttribute("ProjectId", erpRfqrow.getAttribute("ProjectId"));
//                newRow.setAttribute("DepartmentId", erpRfqrow.getAttribute("DepartmentId"));
//                newRow.setAttribute("DemandLinesSno", erpRfqrow.getAttribute("DemandLinesSno"));
//                newRow.setAttribute("SupplierItemName", erpRfqrow.getAttribute("SupplierItemName"));
//                newRow.setAttribute("ChartOfAccountId", erpRfqrow.getAttribute("ChartOfAccountId"));
//                newRow.setAttribute("InventoryOrgSno", erpRfqrow.getAttribute("InventoryOrgSno"));
//                newRow.setAttribute("SubInventoryOrgSno", erpRfqrow.getAttribute("SubinventoryOrgSno"));
//                newRow.setAttribute("Remarks", erpRfqrow.getAttribute("Remarks"));
//                newRow.setAttribute("StatusSno", erpRfqrow.getAttribute("StatusSno"));
//                getScmPurchaseOrderLinesVO().insertRow(newRow);
//            }

            /**/
        }
//        getscmp
    }

    /**
     * Gets the attribute value for EMPLOYEE_SNO using the alias name EmployeeSno.
     * @return the EMPLOYEE_SNO
     */
    public Integer getEmployeeSno() {
        return (Integer) getAttributeInternal(EMPLOYEESNO);
    }

    /**
     * Sets <code>value</code> as attribute value for EMPLOYEE_SNO using the alias name EmployeeSno.
     * @param value value to set the EMPLOYEE_SNO
     */
    public void setEmployeeSno(Integer value) {
        setAttributeInternal(EMPLOYEESNO, value);
    }

    /**
     * Gets the attribute value for REFERENCE_NO using the alias name ReferenceNo.
     * @return the REFERENCE_NO
     */
    public String getReferenceNo() {
        return (String) getAttributeInternal(REFERENCENO);
    }

    /**
     * Sets <code>value</code> as attribute value for REFERENCE_NO using the alias name ReferenceNo.
     * @param value value to set the REFERENCE_NO
     */
    public void setReferenceNo(String value) {
        setAttributeInternal(REFERENCENO, value);
    }

    /**
     * Gets the attribute value for BILL_TO_SNO using the alias name BillToSno.
     * @return the BILL_TO_SNO
     */
    public Integer getBillToSno() {
        return (Integer) getAttributeInternal(BILLTOSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for BILL_TO_SNO using the alias name BillToSno.
     * @param value value to set the BILL_TO_SNO
     */
    public void setBillToSno(Integer value) {
        setAttributeInternal(BILLTOSNO, value);
    }

    /**
     * Gets the attribute value for SHIP_TO_SNO using the alias name ShipToSno.
     * @return the SHIP_TO_SNO
     */
    public Integer getShipToSno() {
        return (Integer) getAttributeInternal(SHIPTOSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIP_TO_SNO using the alias name ShipToSno.
     * @param value value to set the SHIP_TO_SNO
     */
    public void setShipToSno(Integer value) {
        setAttributeInternal(SHIPTOSNO, value);
    }

    /**
     * Gets the attribute value for DEMAND_HEADER_SNO using the alias name DemandHeaderSno.
     * @return the DEMAND_HEADER_SNO
     */
    public Integer getDemandHeaderSno() {
        return (Integer) getAttributeInternal(DEMANDHEADERSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for DEMAND_HEADER_SNO using the alias name DemandHeaderSno.
     * @param value value to set the DEMAND_HEADER_SNO
     */
    public void setDemandHeaderSno(Integer value) {
        setAttributeInternal(DEMANDHEADERSNO, value);
    }

    /**
     * Gets the attribute value for COMPARE_HEADER_SNO using the alias name CompareHeaderSno.
     * @return the COMPARE_HEADER_SNO
     */
    public Integer getCompareHeaderSno() {
        return (Integer) getAttributeInternal(COMPAREHEADERSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPARE_HEADER_SNO using the alias name CompareHeaderSno.
     * @param value value to set the COMPARE_HEADER_SNO
     */
    public void setCompareHeaderSno(Integer value) {
        setAttributeInternal(COMPAREHEADERSNO, value);
    }

    /**
     * Gets the attribute value for PO_DATE using the alias name PoDate.
     * @return the PO_DATE
     */
    public Timestamp getPoDate() {
        return (Timestamp) getAttributeInternal(PODATE);
    }

    /**
     * Sets <code>value</code> as attribute value for PO_DATE using the alias name PoDate.
     * @param value value to set the PO_DATE
     */
    public void setPoDate(Timestamp value) {
        setAttributeInternal(PODATE, value);
    }

    /**
     * Gets the attribute value for ORDER_TYPE_SNO using the alias name OrderTypeSno.
     * @return the ORDER_TYPE_SNO
     */
    public Integer getOrderTypeSno() {
        return (Integer) getAttributeInternal(ORDERTYPESNO);
    }

    /**
     * Sets <code>value</code> as attribute value for ORDER_TYPE_SNO using the alias name OrderTypeSno.
     * @param value value to set the ORDER_TYPE_SNO
     */
    public void setOrderTypeSno(Integer value) {
        setAttributeInternal(ORDERTYPESNO, value);
    }

    /**
     * Gets the attribute value for STATUS_ID using the alias name StatusId.
     * @return the STATUS_ID
     */
    public Integer getStatusId() {
        return (Integer) getAttributeInternal(STATUSID);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS_ID using the alias name StatusId.
     * @param value value to set the STATUS_ID
     */
    public void setStatusId(Integer value) {
        setAttributeInternal(STATUSID, value);
    }

    /**
     * Gets the attribute value for SUPPLIER_SNO using the alias name SupplierSno.
     * @return the SUPPLIER_SNO
     */
    public Integer getSupplierSno() {
        return (Integer) getAttributeInternal(SUPPLIERSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for SUPPLIER_SNO using the alias name SupplierSno.
     * @param value value to set the SUPPLIER_SNO
     */
    public void setSupplierSno(Integer value) {
        setAttributeInternal(SUPPLIERSNO, value);
        setRfqHeaderSno(null);
        setDemandHeaderSno(null);
        setCompareHeaderSno(null);
//        setRfqHeaderSno(null);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for LOCATION_ID using the alias name LocationId.
     * @return the LOCATION_ID
     */
    public Integer getLocationId() {
        return (Integer) getAttributeInternal(LOCATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for LOCATION_ID using the alias name LocationId.
     * @param value value to set the LOCATION_ID
     */
    public void setLocationId(Integer value) {
        setAttributeInternal(LOCATIONID, value);
        setCompanyId(doGetCompanyIDByLocation(value==null?0:value.intValue(), getGlobalCompanyId()));
        setRfqHeaderSno(null);
        setDemandHeaderSno(null);
        setCompareHeaderSno(null);
    }

    /**
     * Gets the attribute value for GLOBAL_COMPANY_ID using the alias name GlobalCompanyId.
     * @return the GLOBAL_COMPANY_ID
     */
    public Integer getGlobalCompanyId() {
        return (Integer) getAttributeInternal(GLOBALCOMPANYID);
    }

    /**
     * Sets <code>value</code> as attribute value for GLOBAL_COMPANY_ID using the alias name GlobalCompanyId.
     * @param value value to set the GLOBAL_COMPANY_ID
     */
    public void setGlobalCompanyId(Integer value) {
        setAttributeInternal(GLOBALCOMPANYID, value);
    }

    /**
     * Gets the attribute value for COMPANY_ID using the alias name CompanyId.
     * @return the COMPANY_ID
     */
    public Integer getCompanyId() {
        return (Integer) getAttributeInternal(COMPANYID);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANY_ID using the alias name CompanyId.
     * @param value value to set the COMPANY_ID
     */
    public void setCompanyId(Integer value) {
        setAttributeInternal(COMPANYID, value);
    }

    /**
     * Gets the attribute value for TEMP_PROJECT_ID using the alias name TempProjectId.
     * @return the TEMP_PROJECT_ID
     */
    public Integer getTempProjectId() {
        return (Integer) getAttributeInternal(TEMPPROJECTID);
    }

    /**
     * Sets <code>value</code> as attribute value for TEMP_PROJECT_ID using the alias name TempProjectId.
     * @param value value to set the TEMP_PROJECT_ID
     */
    public void setTempProjectId(Integer value) {
        setAttributeInternal(TEMPPROJECTID, value);
    }

    /**
     * Gets the attribute value for TEMP_DEPARTMENT_ID using the alias name TempDepartmentId.
     * @return the TEMP_DEPARTMENT_ID
     */
    public Integer getTempDepartmentId() {
        return (Integer) getAttributeInternal(TEMPDEPARTMENTID);
    }

    /**
     * Sets <code>value</code> as attribute value for TEMP_DEPARTMENT_ID using the alias name TempDepartmentId.
     * @param value value to set the TEMP_DEPARTMENT_ID
     */
    public void setTempDepartmentId(Integer value) {
        setAttributeInternal(TEMPDEPARTMENTID, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Integer getCreatedBy() {
        return (Integer) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Integer value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Integer getLastUpdatedBy() {
        return (Integer) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Integer value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @param value value to set the LAST_UPDATED_DATE
     */
    public void setLastUpdatedDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for IS_SUPERVISED using the alias name IsSupervised.
     * @return the IS_SUPERVISED
     */
    public String getIsSupervised() {
        return (String) getAttributeInternal(ISSUPERVISED);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_SUPERVISED using the alias name IsSupervised.
     * @param value value to set the IS_SUPERVISED
     */
    public void setIsSupervised(String value) {
        setAttributeInternal(ISSUPERVISED, value);
    }

    /**
     * Gets the attribute value for SUPERVISED_BY using the alias name SupervisedBy.
     * @return the SUPERVISED_BY
     */
    public Integer getSupervisedBy() {
        return (Integer) getAttributeInternal(SUPERVISEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for SUPERVISED_BY using the alias name SupervisedBy.
     * @param value value to set the SUPERVISED_BY
     */
    public void setSupervisedBy(Integer value) {
        setAttributeInternal(SUPERVISEDBY, value);
    }

    /**
     * Gets the attribute value for SUPERVISED_DATE using the alias name SupervisedDate.
     * @return the SUPERVISED_DATE
     */
    public Timestamp getSupervisedDate() {
        return (Timestamp) getAttributeInternal(SUPERVISEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for SUPERVISED_DATE using the alias name SupervisedDate.
     * @param value value to set the SUPERVISED_DATE
     */
    public void setSupervisedDate(Timestamp value) {
        setAttributeInternal(SUPERVISEDDATE, value);
    }

    /**
     * Gets the attribute value for IS_UNSUPERVISED using the alias name IsUnsupervised.
     * @return the IS_UNSUPERVISED
     */
    public String getIsUnsupervised() {
        return (String) getAttributeInternal(ISUNSUPERVISED);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_UNSUPERVISED using the alias name IsUnsupervised.
     * @param value value to set the IS_UNSUPERVISED
     */
    public void setIsUnsupervised(String value) {
        setAttributeInternal(ISUNSUPERVISED, value);
    }

    /**
     * Gets the attribute value for UN_SUPERVISED_BY using the alias name UnSupervisedBy.
     * @return the UN_SUPERVISED_BY
     */
    public Integer getUnSupervisedBy() {
        return (Integer) getAttributeInternal(UNSUPERVISEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for UN_SUPERVISED_BY using the alias name UnSupervisedBy.
     * @param value value to set the UN_SUPERVISED_BY
     */
    public void setUnSupervisedBy(Integer value) {
        setAttributeInternal(UNSUPERVISEDBY, value);
    }

    /**
     * Gets the attribute value for UN_SUPERVISED_DATE using the alias name UnSupervisedDate.
     * @return the UN_SUPERVISED_DATE
     */
    public Timestamp getUnSupervisedDate() {
        return (Timestamp) getAttributeInternal(UNSUPERVISEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for UN_SUPERVISED_DATE using the alias name UnSupervisedDate.
     * @param value value to set the UN_SUPERVISED_DATE
     */
    public void setUnSupervisedDate(Timestamp value) {
        setAttributeInternal(UNSUPERVISEDDATE, value);
    }

    /**
     * Gets the attribute value for IS_CANCELLED using the alias name IsCancelled.
     * @return the IS_CANCELLED
     */
    public String getIsCancelled() {
        return (String) getAttributeInternal(ISCANCELLED);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_CANCELLED using the alias name IsCancelled.
     * @param value value to set the IS_CANCELLED
     */
    public void setIsCancelled(String value) {
        setAttributeInternal(ISCANCELLED, value);
    }

    /**
     * Gets the attribute value for CANCELLED_BY using the alias name CancelledBy.
     * @return the CANCELLED_BY
     */
    public Integer getCancelledBy() {
        return (Integer) getAttributeInternal(CANCELLEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CANCELLED_BY using the alias name CancelledBy.
     * @param value value to set the CANCELLED_BY
     */
    public void setCancelledBy(Integer value) {
        setAttributeInternal(CANCELLEDBY, value);
    }

    /**
     * Gets the attribute value for CANCELLED_DATE using the alias name CancelledDate.
     * @return the CANCELLED_DATE
     */
    public Timestamp getCancelledDate() {
        return (Timestamp) getAttributeInternal(CANCELLEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CANCELLED_DATE using the alias name CancelledDate.
     * @param value value to set the CANCELLED_DATE
     */
    public void setCancelledDate(Timestamp value) {
        setAttributeInternal(CANCELLEDDATE, value);
    }

    /**
     * Gets the attribute value for APPROVAL_STATUS_SNO using the alias name ApprovalStatusSno.
     * @return the APPROVAL_STATUS_SNO
     */
    public Integer getApprovalStatusSno() {
        return (Integer) getAttributeInternal(APPROVALSTATUSSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for APPROVAL_STATUS_SNO using the alias name ApprovalStatusSno.
     * @param value value to set the APPROVAL_STATUS_SNO
     */
    public void setApprovalStatusSno(Integer value) {
        setAttributeInternal(APPROVALSTATUSSNO, value);
    }

    /**
     * Gets the attribute value for PO_TYPE_SNO using the alias name PoTypeSno.
     * @return the PO_TYPE_SNO
     */
    public String getPoTypeSno() {
        return (String) getAttributeInternal(POTYPESNO);
    }

    /**
     * Sets <code>value</code> as attribute value for PO_TYPE_SNO using the alias name PoTypeSno.
     * @param value value to set the PO_TYPE_SNO
     */
    public void setPoTypeSno(String value) {
        setAttributeInternal(POTYPESNO, value);
    }

    /**
     * Gets the attribute value for FOB_TERM_SNO using the alias name FobTermSno.
     * @return the FOB_TERM_SNO
     */
    public Integer getFobTermSno() {
        return (Integer) getAttributeInternal(FOBTERMSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for FOB_TERM_SNO using the alias name FobTermSno.
     * @param value value to set the FOB_TERM_SNO
     */
    public void setFobTermSno(Integer value) {
        setAttributeInternal(FOBTERMSNO, value);
    }

    /**
     * Gets the attribute value for FREIGHT_TERM_SNO using the alias name FreightTermSno.
     * @return the FREIGHT_TERM_SNO
     */
    public Integer getFreightTermSno() {
        return (Integer) getAttributeInternal(FREIGHTTERMSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for FREIGHT_TERM_SNO using the alias name FreightTermSno.
     * @param value value to set the FREIGHT_TERM_SNO
     */
    public void setFreightTermSno(Integer value) {
        setAttributeInternal(FREIGHTTERMSNO, value);
    }

    /**
     * Gets the attribute value for COURIER_SNO using the alias name CourierSno.
     * @return the COURIER_SNO
     */
    public Integer getCourierSno() {
        return (Integer) getAttributeInternal(COURIERSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for COURIER_SNO using the alias name CourierSno.
     * @param value value to set the COURIER_SNO
     */
    public void setCourierSno(Integer value) {
        setAttributeInternal(COURIERSNO, value);
    }

    /**
     * Gets the attribute value for PAYMENT_TERM_HEADER_SNO using the alias name PaymentTermHeaderSno.
     * @return the PAYMENT_TERM_HEADER_SNO
     */
    public Integer getPaymentTermHeaderSno() {
        return (Integer) getAttributeInternal(PAYMENTTERMHEADERSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for PAYMENT_TERM_HEADER_SNO using the alias name PaymentTermHeaderSno.
     * @param value value to set the PAYMENT_TERM_HEADER_SNO
     */
    public void setPaymentTermHeaderSno(Integer value) {
        setAttributeInternal(PAYMENTTERMHEADERSNO, value);
    }

    /**
     * Gets the attribute value for TXT_LOCATION_NAME using the alias name txtLocationName.
     * @return the TXT_LOCATION_NAME
     */
    public String gettxtLocationName() {
        return (String) getAttributeInternal(TXTLOCATIONNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_LOCATION_NAME using the alias name txtLocationName.
     * @param value value to set the TXT_LOCATION_NAME
     */
    public void settxtLocationName(String value) {
        setAttributeInternal(TXTLOCATIONNAME, value);
    }

    /**
     * Gets the attribute value for TXT_TEMP_DEPARTMENT_NAME using the alias name txtTempDepartmentName.
     * @return the TXT_TEMP_DEPARTMENT_NAME
     */
    public String gettxtTempDepartmentName() {
        return (String) getAttributeInternal(TXTTEMPDEPARTMENTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_TEMP_DEPARTMENT_NAME using the alias name txtTempDepartmentName.
     * @param value value to set the TXT_TEMP_DEPARTMENT_NAME
     */
    public void settxtTempDepartmentName(String value) {
        setAttributeInternal(TXTTEMPDEPARTMENTNAME, value);
    }

    /**
     * Gets the attribute value for TXT_TEMP_PROJECT_NAME using the alias name txtTempProjectName.
     * @return the TXT_TEMP_PROJECT_NAME
     */
    public String gettxtTempProjectName() {
        return (String) getAttributeInternal(TXTTEMPPROJECTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_TEMP_PROJECT_NAME using the alias name txtTempProjectName.
     * @param value value to set the TXT_TEMP_PROJECT_NAME
     */
    public void settxtTempProjectName(String value) {
        setAttributeInternal(TXTTEMPPROJECTNAME, value);
    }

    /**
     * Gets the attribute value for txt_Payment_Term_Name using the alias name txtPaymentTermName.
     * @return the txt_Payment_Term_Name
     */
    public String gettxtPaymentTermName() {
        return (String) getAttributeInternal(TXTPAYMENTTERMNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for txt_Payment_Term_Name using the alias name txtPaymentTermName.
     * @param value value to set the txt_Payment_Term_Name
     */
    public void settxtPaymentTermName(String value) {
        setAttributeInternal(TXTPAYMENTTERMNAME, value);
    }

    /**
     * Gets the attribute value for txt_Freight_Term_Name using the alias name txtFreightTermName.
     * @return the txt_Freight_Term_Name
     */
    public String gettxtFreightTermName() {
        return (String) getAttributeInternal(TXTFREIGHTTERMNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for txt_Freight_Term_Name using the alias name txtFreightTermName.
     * @param value value to set the txt_Freight_Term_Name
     */
    public void settxtFreightTermName(String value) {
        setAttributeInternal(TXTFREIGHTTERMNAME, value);
    }

    /**
     * Gets the attribute value for txt_Fob_Term_Name using the alias name txtFobTermName.
     * @return the txt_Fob_Term_Name
     */
    public String gettxtFobTermName() {
        return (String) getAttributeInternal(TXTFOBTERMNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for txt_Fob_Term_Name using the alias name txtFobTermName.
     * @param value value to set the txt_Fob_Term_Name
     */
    public void settxtFobTermName(String value) {
        setAttributeInternal(TXTFOBTERMNAME, value);
    }

    /**
     * Gets the attribute value for txt_Rfq_Header_Code using the alias name txtRfqHeaderCode.
     * @return the txt_Rfq_Header_Code
     */
    public Integer gettxtRfqHeaderCode() {
        return (Integer) getAttributeInternal(TXTRFQHEADERCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for txt_Rfq_Header_Code using the alias name txtRfqHeaderCode.
     * @param value value to set the txt_Rfq_Header_Code
     */
    public void settxtRfqHeaderCode(Integer value) {
        setAttributeInternal(TXTRFQHEADERCODE, value);
    }

    /**
     * Gets the attribute value for txt_Demand_Header_Code using the alias name txtDemandHeaderCode.
     * @return the txt_Demand_Header_Code
     */
    public Integer gettxtDemandHeaderCode() {
        return (Integer) getAttributeInternal(TXTDEMANDHEADERCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for txt_Demand_Header_Code using the alias name txtDemandHeaderCode.
     * @param value value to set the txt_Demand_Header_Code
     */
    public void settxtDemandHeaderCode(Integer value) {
        setAttributeInternal(TXTDEMANDHEADERCODE, value);
    }

    /**
     * Gets the attribute value for txt_Supplier_Name using the alias name txtSupplierName.
     * @return the txt_Supplier_Name
     */
    public String gettxtSupplierName() {
        return (String) getAttributeInternal(TXTSUPPLIERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for txt_Supplier_Name using the alias name txtSupplierName.
     * @param value value to set the txt_Supplier_Name
     */
    public void settxtSupplierName(String value) {
        setAttributeInternal(TXTSUPPLIERNAME, value);
    }

    /**
     * Gets the attribute value for txt_Supplier_Bill_To_Location using the alias name txtSupplierBillToLocation.
     * @return the txt_Supplier_Bill_To_Location
     */
    public String gettxtSupplierBillToLocation() {
        return (String) getAttributeInternal(TXTSUPPLIERBILLTOLOCATION);
    }

    /**
     * Sets <code>value</code> as attribute value for txt_Supplier_Bill_To_Location using the alias name txtSupplierBillToLocation.
     * @param value value to set the txt_Supplier_Bill_To_Location
     */
    public void settxtSupplierBillToLocation(String value) {
        setAttributeInternal(TXTSUPPLIERBILLTOLOCATION, value);
    }

    /**
     * Gets the attribute value for txt_Supplier_Ship_To_Location using the alias name txtSupplierShipToLocation.
     * @return the txt_Supplier_Ship_To_Location
     */
    public String gettxtSupplierShipToLocation() {
        return (String) getAttributeInternal(TXTSUPPLIERSHIPTOLOCATION);
    }

    /**
     * Sets <code>value</code> as attribute value for txt_Supplier_Ship_To_Location using the alias name txtSupplierShipToLocation.
     * @param value value to set the txt_Supplier_Ship_To_Location
     */
    public void settxtSupplierShipToLocation(String value) {
        setAttributeInternal(TXTSUPPLIERSHIPTOLOCATION, value);
    }

    /**
     * Gets the attribute value for DELIVERY_TERM_SNO using the alias name DeliveryTermSno.
     * @return the DELIVERY_TERM_SNO
     */
    public Integer getDeliveryTermSno() {
        return (Integer) getAttributeInternal(DELIVERYTERMSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for DELIVERY_TERM_SNO using the alias name DeliveryTermSno.
     * @param value value to set the DELIVERY_TERM_SNO
     */
    public void setDeliveryTermSno(Integer value) {
        setAttributeInternal(DELIVERYTERMSNO, value);
    }

    /**
     * Gets the attribute value for TXT_DELIVERY_TERM_NAME using the alias name txtDeliveryTermName.
     * @return the TXT_DELIVERY_TERM_NAME
     */
    public String gettxtDeliveryTermName() {
        return (String) getAttributeInternal(TXTDELIVERYTERMNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_DELIVERY_TERM_NAME using the alias name txtDeliveryTermName.
     * @param value value to set the TXT_DELIVERY_TERM_NAME
     */
    public void settxtDeliveryTermName(String value) {
        setAttributeInternal(TXTDELIVERYTERMNAME, value);
    }

    /**
     * Gets the attribute value for TXT_ORDER_TYPE_NAME using the alias name txtOrderTypeName.
     * @return the TXT_ORDER_TYPE_NAME
     */
    public String gettxtOrderTypeName() {
        return (String) getAttributeInternal(TXTORDERTYPENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_ORDER_TYPE_NAME using the alias name txtOrderTypeName.
     * @param value value to set the TXT_ORDER_TYPE_NAME
     */
    public void settxtOrderTypeName(String value) {
        setAttributeInternal(TXTORDERTYPENAME, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ScmPurchaseOrderChargesVO.
     */
    public RowIterator getScmPurchaseOrderChargesVO() {
        return (RowIterator) getAttributeInternal(SCMPURCHASEORDERCHARGESVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ScmPurchaseOrderDiscountVO.
     */
    public RowIterator getScmPurchaseOrderDiscountVO() {
        return (RowIterator) getAttributeInternal(SCMPURCHASEORDERDISCOUNTVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ScmPurchaseOrderLinesVO.
     */
    public RowIterator getScmPurchaseOrderLinesVO() {
        return (RowIterator) getAttributeInternal(SCMPURCHASEORDERLINESVO);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link AdminCompanyVO.
     */
    public Row getAdminCompanyVO() {
        return (Row) getAttributeInternal(ADMINCOMPANYVO);
    }

    /**
     * Sets the master-detail link AdminCompanyVO between this object and <code>value</code>.
     */
    public void setAdminCompanyVO(Row value) {
        setAttributeInternal(ADMINCOMPANYVO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link AdminCompanyVO1.
     */
    public Row getAdminCompanyVO1() {
        return (Row) getAttributeInternal(ADMINCOMPANYVO1);
    }

    /**
     * Sets the master-detail link AdminCompanyVO1 between this object and <code>value</code>.
     */
    public void setAdminCompanyVO1(Row value) {
        setAttributeInternal(ADMINCOMPANYVO1, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link GlProjectsVO.
     */
    public Row getGlProjectsVO() {
        return (Row) getAttributeInternal(GLPROJECTSVO);
    }

    /**
     * Sets the master-detail link GlProjectsVO between this object and <code>value</code>.
     */
    public void setGlProjectsVO(Row value) {
        setAttributeInternal(GLPROJECTSVO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link ScmPurchaseRfqHeaderVO.
     */
    public Row getScmPurchaseRfqHeaderVO() {
        return (Row) getAttributeInternal(SCMPURCHASERFQHEADERVO);
    }

    /**
     * Sets the master-detail link ScmPurchaseRfqHeaderVO between this object and <code>value</code>.
     */
    public void setScmPurchaseRfqHeaderVO(Row value) {
        setAttributeInternal(SCMPURCHASERFQHEADERVO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link ScmPaymentTermHeaderVO.
     */
    public Row getScmPaymentTermHeaderVO() {
        return (Row) getAttributeInternal(SCMPAYMENTTERMHEADERVO);
    }

    /**
     * Sets the master-detail link ScmPaymentTermHeaderVO between this object and <code>value</code>.
     */
    public void setScmPaymentTermHeaderVO(Row value) {
        setAttributeInternal(SCMPAYMENTTERMHEADERVO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link ScmFreightTermVO.
     */
    public Row getScmFreightTermVO() {
        return (Row) getAttributeInternal(SCMFREIGHTTERMVO);
    }

    /**
     * Sets the master-detail link ScmFreightTermVO between this object and <code>value</code>.
     */
    public void setScmFreightTermVO(Row value) {
        setAttributeInternal(SCMFREIGHTTERMVO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link ScmFobTermVO.
     */
    public Row getScmFobTermVO() {
        return (Row) getAttributeInternal(SCMFOBTERMVO);
    }

    /**
     * Sets the master-detail link ScmFobTermVO between this object and <code>value</code>.
     */
    public void setScmFobTermVO(Row value) {
        setAttributeInternal(SCMFOBTERMVO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link ScmPurchaseDemandHeaderVO.
     */
    public Row getScmPurchaseDemandHeaderVO() {
        return (Row) getAttributeInternal(SCMPURCHASEDEMANDHEADERVO);
    }

    /**
     * Sets the master-detail link ScmPurchaseDemandHeaderVO between this object and <code>value</code>.
     */
    public void setScmPurchaseDemandHeaderVO(Row value) {
        setAttributeInternal(SCMPURCHASEDEMANDHEADERVO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link ScmSupplierSitesVO.
     */
    public Row getScmSupplierSitesVO() {
        return (Row) getAttributeInternal(SCMSUPPLIERSITESVO);
    }

    /**
     * Sets the master-detail link ScmSupplierSitesVO between this object and <code>value</code>.
     */
    public void setScmSupplierSitesVO(Row value) {
        setAttributeInternal(SCMSUPPLIERSITESVO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link ScmSupplierSitesVO1.
     */
    public Row getScmSupplierSitesVO1() {
        return (Row) getAttributeInternal(SCMSUPPLIERSITESVO1);
    }

    /**
     * Sets the master-detail link ScmSupplierSitesVO1 between this object and <code>value</code>.
     */
    public void setScmSupplierSitesVO1(Row value) {
        setAttributeInternal(SCMSUPPLIERSITESVO1, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link ScmDeliveryTermVO.
     */
    public Row getScmDeliveryTermVO() {
        return (Row) getAttributeInternal(SCMDELIVERYTERMVO);
    }

    /**
     * Sets the master-detail link ScmDeliveryTermVO between this object and <code>value</code>.
     */
    public void setScmDeliveryTermVO(Row value) {
        setAttributeInternal(SCMDELIVERYTERMVO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link ScmOrderTypeVO.
     */
    public Row getScmOrderTypeVO() {
        return (Row) getAttributeInternal(SCMORDERTYPEVO);
    }

    /**
     * Sets the master-detail link ScmOrderTypeVO between this object and <code>value</code>.
     */
    public void setScmOrderTypeVO(Row value) {
        setAttributeInternal(SCMORDERTYPEVO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link ScmSupplierVO.
     */
    public Row getScmSupplierVO() {
        return (Row) getAttributeInternal(SCMSUPPLIERVO);
    }

    /**
     * Sets the master-detail link ScmSupplierVO between this object and <code>value</code>.
     */
    public void setScmSupplierVO(Row value) {
        setAttributeInternal(SCMSUPPLIERVO, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSysGeneralValuePOTypeVO.
     */
    public RowSet getAccSysGeneralValuePOTypeVO() {
        return (RowSet) getAttributeInternal(ACCSYSGENERALVALUEPOTYPEVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSysSystemParameterVO.
     */
    public RowSet getAccSysSystemParameterVO() {
        return (RowSet) getAttributeInternal(ACCSYSSYSTEMPARAMETERVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccAdminCompanyForCompVO.
     */
    public RowSet getAccAdminCompanyForCompVO() {
        return (RowSet) getAttributeInternal(ACCADMINCOMPANYFORCOMPVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccGlProjectsVO.
     */
    public RowSet getAccGlProjectsVO() {
        return (RowSet) getAttributeInternal(ACCGLPROJECTSVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccScmPaymentTermHeaderVO.
     */
    public RowSet getAccScmPaymentTermHeaderVO() {
        return (RowSet) getAttributeInternal(ACCSCMPAYMENTTERMHEADERVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccScmFreightTermVO.
     */
    public RowSet getAccScmFreightTermVO() {
        return (RowSet) getAttributeInternal(ACCSCMFREIGHTTERMVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccScmFobTermVO.
     */
    public RowSet getAccScmFobTermVO() {
        return (RowSet) getAttributeInternal(ACCSCMFOBTERMVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccScmPurchaseRfqHeaderVO.
     */
    public RowSet getAccScmPurchaseRfqHeaderVO() {
        return (RowSet) getAttributeInternal(ACCSCMPURCHASERFQHEADERVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccScmPurchaseDemandHeaderVO.
     */
    public RowSet getAccScmPurchaseDemandHeaderVO() {
        return (RowSet) getAttributeInternal(ACCSCMPURCHASEDEMANDHEADERVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccAdminCompanyVO.
     */
    public RowSet getAccAdminCompanyVO() {
        return (RowSet) getAttributeInternal(ACCADMINCOMPANYVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccScmSupplierVO.
     */
    public RowSet getAccScmSupplierVO() {
        return (RowSet) getAttributeInternal(ACCSCMSUPPLIERVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccAdminCompanyDept.
     */
    public RowSet getAccAdminCompanyDept() {
        return (RowSet) getAttributeInternal(ACCADMINCOMPANYDEPT);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSysApprovalStatusVO.
     */
    public RowSet getAccSysApprovalStatusVO() {
        return (RowSet) getAttributeInternal(ACCSYSAPPROVALSTATUSVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccScmSupplierSitesVO.
     */
    public RowSet getAccScmSupplierSitesVO() {
        return (RowSet) getAttributeInternal(ACCSCMSUPPLIERSITESVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccScmSupplierSitesShipToVO.
     */
    public RowSet getAccScmSupplierSitesShipToVO() {
        return (RowSet) getAttributeInternal(ACCSCMSUPPLIERSITESSHIPTOVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccScmDeliveryTermVO.
     */
    public RowSet getAccScmDeliveryTermVO() {
        return (RowSet) getAttributeInternal(ACCSCMDELIVERYTERMVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccScmOrderTypeVO.
     */
    public RowSet getAccScmOrderTypeVO() {
        return (RowSet) getAttributeInternal(ACCSCMORDERTYPEVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccScmPurchaseBidCompHeaderVO.
     */
    public RowSet getAccScmPurchaseBidCompHeaderVO() {
        return (RowSet) getAttributeInternal(ACCSCMPURCHASEBIDCOMPHEADERVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccScmPurchaseBidCompSupplierVO.
     */
    public RowSet getAccScmPurchaseBidCompSupplierVO() {
        return (RowSet) getAttributeInternal(ACCSCMPURCHASEBIDCOMPSUPPLIERVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccScmPurchaseBidLinesVO.
     */
    public RowSet getAccScmPurchaseBidLinesVO() {
        return (RowSet) getAttributeInternal(ACCSCMPURCHASEBIDLINESVO);
    }


}

