package erpscm.modelscm.scmqvo.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Oct 03 15:22:29 PKT 2020
// ---------------------------------------------------------------------
public interface CustomerTypeForTaxCatQVORow extends Row {
    void doErpAssignSingleCustTypeToTaxType();
}

