package erpscm.modelscm.scmeo;

import erpadm.modeladm.admeo.SmCountryImpl;

import erpglobals.modelglobals.ERPEntityImpl;

import erpglobals.modelglobals.ERPGlobalPLSQLClass;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Aug 29 16:14:02 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ScmCustomerImpl extends ERPEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        CustomerSno,
        CustomerShortCode,
        CustomerName,
        CustomerShortName,
        PhoneNo,
        Mobile,
        Email,
        Fax,
        CountrySno,
        CitySno,
        CreatedBy,
        CreatedDate,
        LastUpdatedBy,
        LastUpdatedDate,
        ChartOfAccountId,
        CompanyId,
        CustomerTypeSno,
        Nationality,
        Dob,
        CnicNo,
        NtnNo,
        BankId,
        BranchId,
        BankAccountNo,
        BankAccountTitle,
        IbanNo,
        SrbPraNo,
        StrnFbrGst,
        FixedDiscountPercent,
        PaymentTermSno,
        DeliveryTermSno,
        CustomerCategorySno,
        CurrencySno,
        ContactPerson,
        IsActive,
        Website,
        CustomerPictureName,
        IsTaxable,
        AccountOpenDate,
        ParentCustomerSno,
        GlobalCompanyCode,
        CnicExpiryDate,
        txtCountryName,
        txtCityName,
        ScmCustomerSites,
        SmCountry;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CUSTOMERSNO = AttributesEnum.CustomerSno.index();
    public static final int CUSTOMERSHORTCODE = AttributesEnum.CustomerShortCode.index();
    public static final int CUSTOMERNAME = AttributesEnum.CustomerName.index();
    public static final int CUSTOMERSHORTNAME = AttributesEnum.CustomerShortName.index();
    public static final int PHONENO = AttributesEnum.PhoneNo.index();
    public static final int MOBILE = AttributesEnum.Mobile.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int FAX = AttributesEnum.Fax.index();
    public static final int COUNTRYSNO = AttributesEnum.CountrySno.index();
    public static final int CITYSNO = AttributesEnum.CitySno.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int CHARTOFACCOUNTID = AttributesEnum.ChartOfAccountId.index();
    public static final int COMPANYID = AttributesEnum.CompanyId.index();
    public static final int CUSTOMERTYPESNO = AttributesEnum.CustomerTypeSno.index();
    public static final int NATIONALITY = AttributesEnum.Nationality.index();
    public static final int DOB = AttributesEnum.Dob.index();
    public static final int CNICNO = AttributesEnum.CnicNo.index();
    public static final int NTNNO = AttributesEnum.NtnNo.index();
    public static final int BANKID = AttributesEnum.BankId.index();
    public static final int BRANCHID = AttributesEnum.BranchId.index();
    public static final int BANKACCOUNTNO = AttributesEnum.BankAccountNo.index();
    public static final int BANKACCOUNTTITLE = AttributesEnum.BankAccountTitle.index();
    public static final int IBANNO = AttributesEnum.IbanNo.index();
    public static final int SRBPRANO = AttributesEnum.SrbPraNo.index();
    public static final int STRNFBRGST = AttributesEnum.StrnFbrGst.index();
    public static final int FIXEDDISCOUNTPERCENT = AttributesEnum.FixedDiscountPercent.index();
    public static final int PAYMENTTERMSNO = AttributesEnum.PaymentTermSno.index();
    public static final int DELIVERYTERMSNO = AttributesEnum.DeliveryTermSno.index();
    public static final int CUSTOMERCATEGORYSNO = AttributesEnum.CustomerCategorySno.index();
    public static final int CURRENCYSNO = AttributesEnum.CurrencySno.index();
    public static final int CONTACTPERSON = AttributesEnum.ContactPerson.index();
    public static final int ISACTIVE = AttributesEnum.IsActive.index();
    public static final int WEBSITE = AttributesEnum.Website.index();
    public static final int CUSTOMERPICTURENAME = AttributesEnum.CustomerPictureName.index();
    public static final int ISTAXABLE = AttributesEnum.IsTaxable.index();
    public static final int ACCOUNTOPENDATE = AttributesEnum.AccountOpenDate.index();
    public static final int PARENTCUSTOMERSNO = AttributesEnum.ParentCustomerSno.index();
    public static final int GLOBALCOMPANYCODE = AttributesEnum.GlobalCompanyCode.index();
    public static final int CNICEXPIRYDATE = AttributesEnum.CnicExpiryDate.index();
    public static final int TXTCOUNTRYNAME = AttributesEnum.txtCountryName.index();
    public static final int TXTCITYNAME = AttributesEnum.txtCityName.index();
    public static final int SCMCUSTOMERSITES = AttributesEnum.ScmCustomerSites.index();
    public static final int SMCOUNTRY = AttributesEnum.SmCountry.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ScmCustomerImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("erpscm.modelscm.scmeo.ScmCustomer");
    }


    /**
     * Gets the attribute value for CustomerSno, using the alias name CustomerSno.
     * @return the value of CustomerSno
     */
    public Integer getCustomerSno() {
        return (Integer) getAttributeInternal(CUSTOMERSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustomerSno.
     * @param value value to set the CustomerSno
     */
    public void setCustomerSno(Integer value) {
        setAttributeInternal(CUSTOMERSNO, value);
    }

    /**
     * Gets the attribute value for CustomerShortCode, using the alias name CustomerShortCode.
     * @return the value of CustomerShortCode
     */
    public Integer getCustomerShortCode() {
        return (Integer) getAttributeInternal(CUSTOMERSHORTCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustomerShortCode.
     * @param value value to set the CustomerShortCode
     */
    public void setCustomerShortCode(Integer value) {
        setAttributeInternal(CUSTOMERSHORTCODE, value);
    }

    /**
     * Gets the attribute value for CustomerName, using the alias name CustomerName.
     * @return the value of CustomerName
     */
    public String getCustomerName() {
        return (String) getAttributeInternal(CUSTOMERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustomerName.
     * @param value value to set the CustomerName
     */
    public void setCustomerName(String value) {
        setAttributeInternal(CUSTOMERNAME, value);
    }

    /**
     * Gets the attribute value for CustomerShortName, using the alias name CustomerShortName.
     * @return the value of CustomerShortName
     */
    public String getCustomerShortName() {
        return (String) getAttributeInternal(CUSTOMERSHORTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustomerShortName.
     * @param value value to set the CustomerShortName
     */
    public void setCustomerShortName(String value) {
        setAttributeInternal(CUSTOMERSHORTNAME, value);
    }

    /**
     * Gets the attribute value for PhoneNo, using the alias name PhoneNo.
     * @return the value of PhoneNo
     */
    public String getPhoneNo() {
        return (String) getAttributeInternal(PHONENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for PhoneNo.
     * @param value value to set the PhoneNo
     */
    public void setPhoneNo(String value) {
        setAttributeInternal(PHONENO, value);
    }

    /**
     * Gets the attribute value for Mobile, using the alias name Mobile.
     * @return the value of Mobile
     */
    public String getMobile() {
        return (String) getAttributeInternal(MOBILE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Mobile.
     * @param value value to set the Mobile
     */
    public void setMobile(String value) {
        setAttributeInternal(MOBILE, value);
    }

    /**
     * Gets the attribute value for Email, using the alias name Email.
     * @return the value of Email
     */
    public String getEmail() {
        return (String) getAttributeInternal(EMAIL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Email.
     * @param value value to set the Email
     */
    public void setEmail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**
     * Gets the attribute value for Fax, using the alias name Fax.
     * @return the value of Fax
     */
    public String getFax() {
        return (String) getAttributeInternal(FAX);
    }

    /**
     * Sets <code>value</code> as the attribute value for Fax.
     * @param value value to set the Fax
     */
    public void setFax(String value) {
        setAttributeInternal(FAX, value);
    }

    /**
     * Gets the attribute value for CountrySno, using the alias name CountrySno.
     * @return the value of CountrySno
     */
    public Integer getCountrySno() {
        return (Integer) getAttributeInternal(COUNTRYSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for CountrySno.
     * @param value value to set the CountrySno
     */
    public void setCountrySno(Integer value) {
        setAttributeInternal(COUNTRYSNO, value);
    }

    /**
     * Gets the attribute value for CitySno, using the alias name CitySno.
     * @return the value of CitySno
     */
    public Integer getCitySno() {
        return (Integer) getAttributeInternal(CITYSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for CitySno.
     * @param value value to set the CitySno
     */
    public void setCitySno(Integer value) {
        setAttributeInternal(CITYSNO, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public Integer getCreatedBy() {
        return (Integer) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Integer value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public Integer getLastUpdatedBy() {
        return (Integer) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Integer value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the value of LastUpdatedDate
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedDate.
     * @param value value to set the LastUpdatedDate
     */
    public void setLastUpdatedDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for ChartOfAccountId, using the alias name ChartOfAccountId.
     * @return the value of ChartOfAccountId
     */
    public Long getChartOfAccountId() {
        return (Long) getAttributeInternal(CHARTOFACCOUNTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ChartOfAccountId.
     * @param value value to set the ChartOfAccountId
     */
    public void setChartOfAccountId(Long value) {
        setAttributeInternal(CHARTOFACCOUNTID, value);
    }

    /**
     * Gets the attribute value for CompanyId, using the alias name CompanyId.
     * @return the value of CompanyId
     */
    public Integer getCompanyId() {
        return (Integer) getAttributeInternal(COMPANYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CompanyId.
     * @param value value to set the CompanyId
     */
    public void setCompanyId(Integer value) {
        setAttributeInternal(COMPANYID, value);
    }

    /**
     * Gets the attribute value for CustomerTypeSno, using the alias name CustomerTypeSno.
     * @return the value of CustomerTypeSno
     */
    public Integer getCustomerTypeSno() {
        return (Integer) getAttributeInternal(CUSTOMERTYPESNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustomerTypeSno.
     * @param value value to set the CustomerTypeSno
     */
    public void setCustomerTypeSno(Integer value) {
        setAttributeInternal(CUSTOMERTYPESNO, value);
    }

    /**
     * Gets the attribute value for Nationality, using the alias name Nationality.
     * @return the value of Nationality
     */
    public String getNationality() {
        return (String) getAttributeInternal(NATIONALITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Nationality.
     * @param value value to set the Nationality
     */
    public void setNationality(String value) {
        setAttributeInternal(NATIONALITY, value);
    }

    /**
     * Gets the attribute value for Dob, using the alias name Dob.
     * @return the value of Dob
     */
    public Timestamp getDob() {
        return (Timestamp) getAttributeInternal(DOB);
    }

    /**
     * Sets <code>value</code> as the attribute value for Dob.
     * @param value value to set the Dob
     */
    public void setDob(Timestamp value) {
        setAttributeInternal(DOB, value);
    }

    /**
     * Gets the attribute value for CnicNo, using the alias name CnicNo.
     * @return the value of CnicNo
     */
    public String getCnicNo() {
        return (String) getAttributeInternal(CNICNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for CnicNo.
     * @param value value to set the CnicNo
     */
    public void setCnicNo(String value) {
        setAttributeInternal(CNICNO, value);
    }

    /**
     * Gets the attribute value for NtnNo, using the alias name NtnNo.
     * @return the value of NtnNo
     */
    public String getNtnNo() {
        return (String) getAttributeInternal(NTNNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for NtnNo.
     * @param value value to set the NtnNo
     */
    public void setNtnNo(String value) {
        setAttributeInternal(NTNNO, value);
    }

    /**
     * Gets the attribute value for BankId, using the alias name BankId.
     * @return the value of BankId
     */
    public Integer getBankId() {
        return (Integer) getAttributeInternal(BANKID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BankId.
     * @param value value to set the BankId
     */
    public void setBankId(Integer value) {
        setAttributeInternal(BANKID, value);
    }

    /**
     * Gets the attribute value for BranchId, using the alias name BranchId.
     * @return the value of BranchId
     */
    public Integer getBranchId() {
        return (Integer) getAttributeInternal(BRANCHID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BranchId.
     * @param value value to set the BranchId
     */
    public void setBranchId(Integer value) {
        setAttributeInternal(BRANCHID, value);
    }

    /**
     * Gets the attribute value for BankAccountNo, using the alias name BankAccountNo.
     * @return the value of BankAccountNo
     */
    public String getBankAccountNo() {
        return (String) getAttributeInternal(BANKACCOUNTNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for BankAccountNo.
     * @param value value to set the BankAccountNo
     */
    public void setBankAccountNo(String value) {
        setAttributeInternal(BANKACCOUNTNO, value);
    }

    /**
     * Gets the attribute value for BankAccountTitle, using the alias name BankAccountTitle.
     * @return the value of BankAccountTitle
     */
    public String getBankAccountTitle() {
        return (String) getAttributeInternal(BANKACCOUNTTITLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for BankAccountTitle.
     * @param value value to set the BankAccountTitle
     */
    public void setBankAccountTitle(String value) {
        setAttributeInternal(BANKACCOUNTTITLE, value);
    }

    /**
     * Gets the attribute value for IbanNo, using the alias name IbanNo.
     * @return the value of IbanNo
     */
    public String getIbanNo() {
        return (String) getAttributeInternal(IBANNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for IbanNo.
     * @param value value to set the IbanNo
     */
    public void setIbanNo(String value) {
        setAttributeInternal(IBANNO, value);
    }

    /**
     * Gets the attribute value for SrbPraNo, using the alias name SrbPraNo.
     * @return the value of SrbPraNo
     */
    public String getSrbPraNo() {
        return (String) getAttributeInternal(SRBPRANO);
    }

    /**
     * Sets <code>value</code> as the attribute value for SrbPraNo.
     * @param value value to set the SrbPraNo
     */
    public void setSrbPraNo(String value) {
        setAttributeInternal(SRBPRANO, value);
    }

    /**
     * Gets the attribute value for StrnFbrGst, using the alias name StrnFbrGst.
     * @return the value of StrnFbrGst
     */
    public String getStrnFbrGst() {
        return (String) getAttributeInternal(STRNFBRGST);
    }

    /**
     * Sets <code>value</code> as the attribute value for StrnFbrGst.
     * @param value value to set the StrnFbrGst
     */
    public void setStrnFbrGst(String value) {
        setAttributeInternal(STRNFBRGST, value);
    }

    /**
     * Gets the attribute value for FixedDiscountPercent, using the alias name FixedDiscountPercent.
     * @return the value of FixedDiscountPercent
     */
    public BigDecimal getFixedDiscountPercent() {
        return (BigDecimal) getAttributeInternal(FIXEDDISCOUNTPERCENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for FixedDiscountPercent.
     * @param value value to set the FixedDiscountPercent
     */
    public void setFixedDiscountPercent(BigDecimal value) {
        setAttributeInternal(FIXEDDISCOUNTPERCENT, value);
    }

    /**
     * Gets the attribute value for PaymentTermSno, using the alias name PaymentTermSno.
     * @return the value of PaymentTermSno
     */
    public Integer getPaymentTermSno() {
        return (Integer) getAttributeInternal(PAYMENTTERMSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for PaymentTermSno.
     * @param value value to set the PaymentTermSno
     */
    public void setPaymentTermSno(Integer value) {
        setAttributeInternal(PAYMENTTERMSNO, value);
    }

    /**
     * Gets the attribute value for DeliveryTermSno, using the alias name DeliveryTermSno.
     * @return the value of DeliveryTermSno
     */
    public Integer getDeliveryTermSno() {
        return (Integer) getAttributeInternal(DELIVERYTERMSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for DeliveryTermSno.
     * @param value value to set the DeliveryTermSno
     */
    public void setDeliveryTermSno(Integer value) {
        setAttributeInternal(DELIVERYTERMSNO, value);
    }

    /**
     * Gets the attribute value for CustomerCategorySno, using the alias name CustomerCategorySno.
     * @return the value of CustomerCategorySno
     */
    public Integer getCustomerCategorySno() {
        return (Integer) getAttributeInternal(CUSTOMERCATEGORYSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustomerCategorySno.
     * @param value value to set the CustomerCategorySno
     */
    public void setCustomerCategorySno(Integer value) {
        setAttributeInternal(CUSTOMERCATEGORYSNO, value);
    }

    /**
     * Gets the attribute value for CurrencySno, using the alias name CurrencySno.
     * @return the value of CurrencySno
     */
    public Integer getCurrencySno() {
        return (Integer) getAttributeInternal(CURRENCYSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for CurrencySno.
     * @param value value to set the CurrencySno
     */
    public void setCurrencySno(Integer value) {
        setAttributeInternal(CURRENCYSNO, value);
    }

    /**
     * Gets the attribute value for ContactPerson, using the alias name ContactPerson.
     * @return the value of ContactPerson
     */
    public String getContactPerson() {
        return (String) getAttributeInternal(CONTACTPERSON);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContactPerson.
     * @param value value to set the ContactPerson
     */
    public void setContactPerson(String value) {
        setAttributeInternal(CONTACTPERSON, value);
    }

    /**
     * Gets the attribute value for IsActive, using the alias name IsActive.
     * @return the value of IsActive
     */
    public String getIsActive() {
        return (String) getAttributeInternal(ISACTIVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsActive.
     * @param value value to set the IsActive
     */
    public void setIsActive(String value) {
        setAttributeInternal(ISACTIVE, value);
    }

    /**
     * Gets the attribute value for Website, using the alias name Website.
     * @return the value of Website
     */
    public String getWebsite() {
        return (String) getAttributeInternal(WEBSITE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Website.
     * @param value value to set the Website
     */
    public void setWebsite(String value) {
        setAttributeInternal(WEBSITE, value);
    }

    /**
     * Gets the attribute value for CustomerPictureName, using the alias name CustomerPictureName.
     * @return the value of CustomerPictureName
     */
    public String getCustomerPictureName() {
        return (String) getAttributeInternal(CUSTOMERPICTURENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustomerPictureName.
     * @param value value to set the CustomerPictureName
     */
    public void setCustomerPictureName(String value) {
        setAttributeInternal(CUSTOMERPICTURENAME, value);
    }

    /**
     * Gets the attribute value for IsTaxable, using the alias name IsTaxable.
     * @return the value of IsTaxable
     */
    public String getIsTaxable() {
        return (String) getAttributeInternal(ISTAXABLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsTaxable.
     * @param value value to set the IsTaxable
     */
    public void setIsTaxable(String value) {
        setAttributeInternal(ISTAXABLE, value);
    }

    /**
     * Gets the attribute value for AccountOpenDate, using the alias name AccountOpenDate.
     * @return the value of AccountOpenDate
     */
    public Timestamp getAccountOpenDate() {
        return (Timestamp) getAttributeInternal(ACCOUNTOPENDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for AccountOpenDate.
     * @param value value to set the AccountOpenDate
     */
    public void setAccountOpenDate(Timestamp value) {
        setAttributeInternal(ACCOUNTOPENDATE, value);
    }

    /**
     * Gets the attribute value for ParentCustomerSno, using the alias name ParentCustomerSno.
     * @return the value of ParentCustomerSno
     */
    public Integer getParentCustomerSno() {
        return (Integer) getAttributeInternal(PARENTCUSTOMERSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParentCustomerSno.
     * @param value value to set the ParentCustomerSno
     */
    public void setParentCustomerSno(Integer value) {
        setAttributeInternal(PARENTCUSTOMERSNO, value);
    }

    /**
     * Gets the attribute value for GlobalCompanyCode, using the alias name GlobalCompanyCode.
     * @return the value of GlobalCompanyCode
     */
    public Integer getGlobalCompanyCode() {
        return (Integer) getAttributeInternal(GLOBALCOMPANYCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for GlobalCompanyCode.
     * @param value value to set the GlobalCompanyCode
     */
    public void setGlobalCompanyCode(Integer value) {
        setAttributeInternal(GLOBALCOMPANYCODE, value);
    }

    /**
     * Gets the attribute value for CnicExpiryDate, using the alias name CnicExpiryDate.
     * @return the value of CnicExpiryDate
     */
    public Timestamp getCnicExpiryDate() {
        return (Timestamp) getAttributeInternal(CNICEXPIRYDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CnicExpiryDate.
     * @param value value to set the CnicExpiryDate
     */
    public void setCnicExpiryDate(Timestamp value) {
        setAttributeInternal(CNICEXPIRYDATE, value);
    }

    /**
     * Gets the attribute value for txtCountryName, using the alias name txtCountryName.
     * @return the value of txtCountryName
     */
    public String gettxtCountryName() {
        return (String) getAttributeInternal(TXTCOUNTRYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtCountryName.
     * @param value value to set the txtCountryName
     */
    public void settxtCountryName(String value) {
        setAttributeInternal(TXTCOUNTRYNAME, value);
    }

    /**
     * Gets the attribute value for txtCityName, using the alias name txtCityName.
     * @return the value of txtCityName
     */
    public String gettxtCityName() {
        return (String) getAttributeInternal(TXTCITYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtCityName.
     * @param value value to set the txtCityName
     */
    public void settxtCityName(String value) {
        setAttributeInternal(TXTCITYNAME, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getScmCustomerSites() {
        return (RowIterator) getAttributeInternal(SCMCUSTOMERSITES);
    }


    /**
     * @return the associated entity erpadm.modeladm.admeo.SmCountryImpl.
     */
    public SmCountryImpl getSmCountry() {
        return (SmCountryImpl) getAttributeInternal(SMCOUNTRY);
    }

    /**
     * Sets <code>value</code> as the associated entity erpadm.modeladm.admeo.SmCountryImpl.
     */
    public void setSmCountry(SmCountryImpl value) {
        setAttributeInternal(SMCOUNTRY, value);
    }


    /**
     * @param customerSno key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer customerSno) {
        return new Key(new Object[] { customerSno });
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }
    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {

        if (operation==DML_INSERT ) {
           String result = ERPGlobalPLSQLClass.doGetPrimaryKeyValueModel(getDBTransaction(), "CUSTOMER_SNO",this.getEntityDef().getSource(), null, null);
           populateAttributeAsChanged(CUSTOMERSNO,  Integer.parseInt(result));
           result = ERPGlobalPLSQLClass.doGetPrimaryKeyValueModel(getDBTransaction(), "CUSTOMER_SHORT_CODE",this.getEntityDef().getSource(), "COMPANY_ID", getCompanyId().toString());
           populateAttributeAsChanged(CUSTOMERSHORTCODE,  Integer.parseInt(result));

        }
        
        super.doDML(operation, e);
    }

}

