package erpscm.modelscm.scmeo;

import erpglobals.modelglobals.ERPEntityImpl;
import erpglobals.modelglobals.ERPGlobalPLSQLClass;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Aug 29 14:57:59 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ScmPaymentTermDiscountImpl extends ERPEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        PaymentTermDiscountSno,
        PaymentTermDueSno,
        PaymentTermHeaderSno,
        DiscountId,
        DiscountPercent,
        DiscountAmount,
        Days,
        Monthss,
        MonthAhead,
        CreatedBy,
        CreatedDate,
        LastUpdatedBy,
        LastUpdatedDate,
        ScmPaymentTermDue;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int PAYMENTTERMDISCOUNTSNO = AttributesEnum.PaymentTermDiscountSno.index();
    public static final int PAYMENTTERMDUESNO = AttributesEnum.PaymentTermDueSno.index();
    public static final int PAYMENTTERMHEADERSNO = AttributesEnum.PaymentTermHeaderSno.index();
    public static final int DISCOUNTID = AttributesEnum.DiscountId.index();
    public static final int DISCOUNTPERCENT = AttributesEnum.DiscountPercent.index();
    public static final int DISCOUNTAMOUNT = AttributesEnum.DiscountAmount.index();
    public static final int DAYS = AttributesEnum.Days.index();
    public static final int MONTHSS = AttributesEnum.Monthss.index();
    public static final int MONTHAHEAD = AttributesEnum.MonthAhead.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int SCMPAYMENTTERMDUE = AttributesEnum.ScmPaymentTermDue.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ScmPaymentTermDiscountImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("erpscm.modelscm.scmeo.ScmPaymentTermDiscount");
    }


    /**
     * Gets the attribute value for PaymentTermDiscountSno, using the alias name PaymentTermDiscountSno.
     * @return the value of PaymentTermDiscountSno
     */
    public Integer getPaymentTermDiscountSno() {
        return (Integer) getAttributeInternal(PAYMENTTERMDISCOUNTSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for PaymentTermDiscountSno.
     * @param value value to set the PaymentTermDiscountSno
     */
    public void setPaymentTermDiscountSno(Integer value) {
        setAttributeInternal(PAYMENTTERMDISCOUNTSNO, value);
    }

    /**
     * Gets the attribute value for PaymentTermDueSno, using the alias name PaymentTermDueSno.
     * @return the value of PaymentTermDueSno
     */
    public Integer getPaymentTermDueSno() {
        return (Integer) getAttributeInternal(PAYMENTTERMDUESNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for PaymentTermDueSno.
     * @param value value to set the PaymentTermDueSno
     */
    public void setPaymentTermDueSno(Integer value) {
        setAttributeInternal(PAYMENTTERMDUESNO, value);
    }

    /**
     * Gets the attribute value for PaymentTermHeaderSno, using the alias name PaymentTermHeaderSno.
     * @return the value of PaymentTermHeaderSno
     */
    public Integer getPaymentTermHeaderSno() {
        return (Integer) getAttributeInternal(PAYMENTTERMHEADERSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for PaymentTermHeaderSno.
     * @param value value to set the PaymentTermHeaderSno
     */
    public void setPaymentTermHeaderSno(Integer value) {
        setAttributeInternal(PAYMENTTERMHEADERSNO, value);
    }

    /**
     * Gets the attribute value for DiscountId, using the alias name DiscountId.
     * @return the value of DiscountId
     */
    public String getDiscountId() {
        return (String) getAttributeInternal(DISCOUNTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DiscountId.
     * @param value value to set the DiscountId
     */
    public void setDiscountId(String value) {
        setAttributeInternal(DISCOUNTID, value);
    }

    /**
     * Gets the attribute value for DiscountPercent, using the alias name DiscountPercent.
     * @return the value of DiscountPercent
     */
    public BigDecimal getDiscountPercent() {
        return (BigDecimal) getAttributeInternal(DISCOUNTPERCENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for DiscountPercent.
     * @param value value to set the DiscountPercent
     */
    public void setDiscountPercent(BigDecimal value) {
        setAttributeInternal(DISCOUNTPERCENT, value);
    }

    /**
     * Gets the attribute value for DiscountAmount, using the alias name DiscountAmount.
     * @return the value of DiscountAmount
     */
    public BigDecimal getDiscountAmount() {
        return (BigDecimal) getAttributeInternal(DISCOUNTAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for DiscountAmount.
     * @param value value to set the DiscountAmount
     */
    public void setDiscountAmount(BigDecimal value) {
        setAttributeInternal(DISCOUNTAMOUNT, value);
    }

    /**
     * Gets the attribute value for Days, using the alias name Days.
     * @return the value of Days
     */
    public BigDecimal getDays() {
        return (BigDecimal) getAttributeInternal(DAYS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Days.
     * @param value value to set the Days
     */
    public void setDays(BigDecimal value) {
        setAttributeInternal(DAYS, value);
    }

    /**
     * Gets the attribute value for Monthss, using the alias name Monthss.
     * @return the value of Monthss
     */
    public BigDecimal getMonthss() {
        return (BigDecimal) getAttributeInternal(MONTHSS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Monthss.
     * @param value value to set the Monthss
     */
    public void setMonthss(BigDecimal value) {
        setAttributeInternal(MONTHSS, value);
    }

    /**
     * Gets the attribute value for MonthAhead, using the alias name MonthAhead.
     * @return the value of MonthAhead
     */
    public BigDecimal getMonthAhead() {
        return (BigDecimal) getAttributeInternal(MONTHAHEAD);
    }

    /**
     * Sets <code>value</code> as the attribute value for MonthAhead.
     * @param value value to set the MonthAhead
     */
    public void setMonthAhead(BigDecimal value) {
        setAttributeInternal(MONTHAHEAD, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public Integer getCreatedBy() {
        return (Integer) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Integer value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public Integer getLastUpdatedBy() {
        return (Integer) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Integer value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the value of LastUpdatedDate
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedDate.
     * @param value value to set the LastUpdatedDate
     */
    public void setLastUpdatedDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * @return the associated entity ScmPaymentTermDueImpl.
     */
    public ScmPaymentTermDueImpl getScmPaymentTermDue() {
        return (ScmPaymentTermDueImpl) getAttributeInternal(SCMPAYMENTTERMDUE);
    }

    /**
     * Sets <code>value</code> as the associated entity ScmPaymentTermDueImpl.
     */
    public void setScmPaymentTermDue(ScmPaymentTermDueImpl value) {
        setAttributeInternal(SCMPAYMENTTERMDUE, value);
    }


    /**
     * @param paymentTermDiscountSno key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer paymentTermDiscountSno) {
        return new Key(new Object[] { paymentTermDiscountSno });
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation == DML_INSERT) {
            
            String result =
                ERPGlobalPLSQLClass.doGetPrimaryKeyValueModel(getDBTransaction(), "PAYMENT_TERM_DISCOUNT_SNO",
                                                              this.getEntityDef().getSource(), null, null);

            populateAttributeAsChanged(PAYMENTTERMDISCOUNTSNO, Integer.parseInt(result));
        
        }        
        super.doDML(operation, e);
    }
}

