package erpscm.modelscm.scmeo;

import erpglobals.modelglobals.ERPEntityImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 23 10:12:45 PKT 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ScmPurchaseOrderChargesImpl extends ERPEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        PoOrderChargesSno,
        PoHeaderSno,
        ChargesGroupSno,
        ChargesSno,
        ChargesAmount,
        CreatedBy,
        CreatedDate,
        LastUpdatedBy,
        LastUpdatedDate,
        ScmPurchaseOrderHeader;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int POORDERCHARGESSNO = AttributesEnum.PoOrderChargesSno.index();
    public static final int POHEADERSNO = AttributesEnum.PoHeaderSno.index();
    public static final int CHARGESGROUPSNO = AttributesEnum.ChargesGroupSno.index();
    public static final int CHARGESSNO = AttributesEnum.ChargesSno.index();
    public static final int CHARGESAMOUNT = AttributesEnum.ChargesAmount.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int SCMPURCHASEORDERHEADER = AttributesEnum.ScmPurchaseOrderHeader.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ScmPurchaseOrderChargesImpl() {
    }

    /**
     * Gets the attribute value for PoOrderChargesSno, using the alias name PoOrderChargesSno.
     * @return the value of PoOrderChargesSno
     */
    public Integer getPoOrderChargesSno() {
        return (Integer) getAttributeInternal(POORDERCHARGESSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for PoOrderChargesSno.
     * @param value value to set the PoOrderChargesSno
     */
    public void setPoOrderChargesSno(Integer value) {
        setAttributeInternal(POORDERCHARGESSNO, value);
    }

    /**
     * Gets the attribute value for PoHeaderSno, using the alias name PoHeaderSno.
     * @return the value of PoHeaderSno
     */
    public Integer getPoHeaderSno() {
        return (Integer) getAttributeInternal(POHEADERSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for PoHeaderSno.
     * @param value value to set the PoHeaderSno
     */
    public void setPoHeaderSno(Integer value) {
        setAttributeInternal(POHEADERSNO, value);
    }

    /**
     * Gets the attribute value for ChargesGroupSno, using the alias name ChargesGroupSno.
     * @return the value of ChargesGroupSno
     */
    public Integer getChargesGroupSno() {
        return (Integer) getAttributeInternal(CHARGESGROUPSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ChargesGroupSno.
     * @param value value to set the ChargesGroupSno
     */
    public void setChargesGroupSno(Integer value) {
        setAttributeInternal(CHARGESGROUPSNO, value);
    }

    /**
     * Gets the attribute value for ChargesSno, using the alias name ChargesSno.
     * @return the value of ChargesSno
     */
    public Integer getChargesSno() {
        return (Integer) getAttributeInternal(CHARGESSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ChargesSno.
     * @param value value to set the ChargesSno
     */
    public void setChargesSno(Integer value) {
        setAttributeInternal(CHARGESSNO, value);
    }

    /**
     * Gets the attribute value for ChargesAmount, using the alias name ChargesAmount.
     * @return the value of ChargesAmount
     */
    public BigDecimal getChargesAmount() {
        return (BigDecimal) getAttributeInternal(CHARGESAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ChargesAmount.
     * @param value value to set the ChargesAmount
     */
    public void setChargesAmount(BigDecimal value) {
        setAttributeInternal(CHARGESAMOUNT, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public Integer getCreatedBy() {
        return (Integer) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Integer value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public Integer getLastUpdatedBy() {
        return (Integer) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Integer value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the value of LastUpdatedDate
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedDate.
     * @param value value to set the LastUpdatedDate
     */
    public void setLastUpdatedDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * @return the associated entity ScmPurchaseOrderHeaderImpl.
     */
    public ScmPurchaseOrderHeaderImpl getScmPurchaseOrderHeader() {
        return (ScmPurchaseOrderHeaderImpl) getAttributeInternal(SCMPURCHASEORDERHEADER);
    }

    /**
     * Sets <code>value</code> as the associated entity ScmPurchaseOrderHeaderImpl.
     */
    public void setScmPurchaseOrderHeader(ScmPurchaseOrderHeaderImpl value) {
        setAttributeInternal(SCMPURCHASEORDERHEADER, value);
    }

    /**
     * @param poOrderChargesSno key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer poOrderChargesSno) {
        return new Key(new Object[] { poOrderChargesSno });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("erpscm.modelscm.scmeo.ScmPurchaseOrderCharges");
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}

