package erpscm.modelscm.scmvo.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 23 10:28:39 PKT 2023
// ---------------------------------------------------------------------
public interface ScmPurchaseRfqSupplierVORow extends Row {
    void doGeneratePoFromBidComp();
}

